### ISSUE TITLE
Example app hangs when dismissing for the second time

### ISSUE THREAD

**Issue by BalestraPatrick** [a2/Spyglass#2]
Steps to reproduce:
1. Tap on a square to open it.
2. Dismiss it interactively by dragging the colored view to the bottom.
3. Tap on a different square to open it.
4. Tap on the "Colors" button at the top left.

The app is now stuck in an undefined state. It is 100% reproducible but the app doesn't crash.

**Comment by a2** [comment]
Fixed by 7936e384adbd70f27800a6ab08df91e8b716c7e7 (v0.0.2).
